name: E2E tests

on:
    pull_request:
        branches:
            - main
    workflow_dispatch: # Allow manual triggering of the workflow

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'
                  cache: 'npm'
              
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.23.4'
                  cache: true
            
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2
              
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y jq
                  go mod download
            
            - name: Build sandbox images
              run: make images
              
            - name: Build the MCP server
              run: make build
              
            - name: Prepare config for GitHub
              run: |
                  # Get the absolute path to the built binary
                  BINARY_PATH="$(pwd)/dist/sandbox-mcp"
                  
                  # If the github-config.json file exists, use it as a template
                  if [ -f "test/github-config.json" ]; then
                    # Replace the placeholder with the actual binary path
                    sed "s|BINARY_PATH_PLACEHOLDER|$BINARY_PATH|g" test/github-config.json > test/config.json
                  else
                    # Otherwise, create a new config.json
                    cat > test/config.json << EOF
                    {
                        "mcpServers": {
                            "sandbox-mcp": {
                                "command": "$BINARY_PATH",
                                "args": [
                                    "--stdio"
                                ]
                            }
                        }
                    }
                    EOF
                  fi
                  
                  # Verify the config
                  echo "Using config.json:"
                  cat test/config.json
            
            - name: Run tests
              run: |
                  chmod +x test/run_tests.sh
                  ./test/run_tests.sh
              
            - name: Handle test failure
              if: failure()
              run: |
                  echo "::error::Tests failed. Check the test logs for details."
                  exit 1
