name: Tests

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Create dist dir
      run: mkdir -p dist

    - name: Build
      run: go build -ldflags="-X 'github.com/pottekkat/sandbox-mcp/internal/version.Version=$$(git describe --tags)' -X 'github.com/pottekkat/sandbox-mcp/internal/version.CommitSHA=$$(git rev-parse --short HEAD)'" -o dist/sandbox-mcp ./cmd/sandbox-mcp/main.go
    
    - uses: actions/upload-artifact@v4
      with:
        name: app-dist
        path: dist/

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: dist/

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Make test script executable
        run: chmod +x ./test/run_tests.sh

      - name: Prepare config
        run: |
          echo '{"mcpServers": {"sandbox-mcp": {"command": "./dist/sandbox-mcp","args": ["--stdio"]}}}' > ./test/config.json

      - name: Run tests
        run: ./test/run_tests.sh
